version: '3.8'

services:
  s_api_mybid_gateway:
    image: api_gateway_image
    container_name: c_api_gateway
    build:
      context: .
      dockerfile: src/Presentation/API/Dockerfile
    ports:
      - "5500:5500"
    networks:
      - mybid-internal
      - mybid-external
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5500
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5500/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      
networks:
  mybid-internal:
    external: true
  mybid-external:
    external: true